Update testRigor.yml
changes made

diff --git a/.github/workflows/testRigor.yml b/.github/workflows/testRigor.yml
--- a/.github/workflows/testRigor.yml
+++ b/.github/workflows/testRigor.yml
@@ -23,48 +23,48 @@ jobs:
             # Runs a set of commands using the runners shell
       - name: Run a multi-line script
         run: |
-          curl -X POST \ 
-        -H 'Content-type: application/json' \ 
-    -H 'auth-token: 1f1719a8-1d5a-485a-942f-287427fc995a' \ 
-    --data '{"forceCancelPreviousTesting":true,"storedValues":{"storedValueName1":"Value"}}' \ 
-    https://api.testrigor.com/api/v1/apps/grCGWgEuevh9eFftG/retest 
+                    curl -X POST \ 
+  -H 'Content-type: application/json' \ 
+  -H 'auth-token: 1f1719a8-1d5a-485a-942f-287427fc995a' \ 
+                   --data '{"forceCancelPreviousTesting":true,"storedValues":{"storedValueName1":"Value"}}' \ 
+                                    https://api.testrigor.com/api/v1/apps/grCGWgEuevh9eFftG/retest 
 
+sleep 10 
+
+while true 
+do 
+  echo " " 
+  echo "===================================" 
+  echo " Checking TestRigor retest" 
+  echo "===================================" 
+  response=$(curl -i -o - -s -X GET 'https://api.testrigor.com/api/v1/apps/grCGWgEuevh9eFftG/status' -H 'auth-token: 1f1719a8-1d5a-485a-942f-287427fc995a' -H 'Accept: application/json') 
+  code=$(echo "$response" | grep HTTP |  awk '{print $2}') 
+  body=$(echo "$response" | grep status) 
+  echo "Status code: " $code 
+  echo "Response: " $body 
+  case $code in 
+    4*|5*) 
+      # 400 or 500 errors 
+      echo "Error calling API" 
+      exit 1 
+      ;; 
+    200) 
+      # 200: successfully finished 
+      echo "Test finished successfully" 
+      exit 0 
+      ;; 
+    227|228) 
+      # 227: New - 228: In progress 
+      echo "Test is not finished yet" 
+      ;; 
+    230) 
+      # 230: Failed 
+      echo "Test finished but failed" 
+      exit 1 
+      ;; 
+    *) 
+      echo "Unknown status" 
+      exit 1 
+    esac 
   sleep 10 
-
-  while true 
-  do 
-    echo " " 
-    echo "===================================" 
-    echo " Checking TestRigor retest" 
-    echo "===================================" 
-    response=$(curl -i -o - -s -X GET 'https://api.testrigor.com/api/v1/apps/grCGWgEuevh9eFftG/status' -H 'auth-token: 1f1719a8-1d5a-485a-942f-287427fc995a' -H 'Accept: application/json') 
-    code=$(echo "$response" | grep HTTP |  awk '{print $2}') 
-    body=$(echo "$response" | grep status) 
-    echo "Status code: " $code 
-    echo "Response: " $body 
-    case $code in 
-      4*|5*) 
-        # 400 or 500 errors 
-        echo "Error calling API" 
-        exit 1 
-        ;; 
-      200) 
-        # 200: successfully finished 
-        echo "Test finished successfully" 
-        exit 0 
-        ;; 
-      227|228) 
-        # 227: New - 228: In progress 
-        echo "Test is not finished yet" 
-        ;; 
-      230) 
-        # 230: Failed 
-        echo "Test finished but failed" 
-        exit 1 
-        ;; 
-      *) 
-        echo "Unknown status" 
-        exit 1 
-      esac 
-    sleep 10 
-  done
+done
